apiVersion: apps/v1
kind: Deployment
metadata:
  name: prism-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: prism-api
  template:
    metadata:
      labels:
        name: prism-api
    spec:
      containers:
        - env:
            - name: API_PORT
              value: "8080"
            - name: API_WORKERS
              value: "4"
            - name: PGHOST
              value: database
            - name: PGPASSWORD
              valueFrom:
                  secretKeyRef:
                      name: prism-api-secret
                      key: postgresql_password
            - name: PGUSER
              valueFrom:
                  secretKeyRef:
                      name: prism-api-secret
                      key: postgresql_username
          image: tcia/prism_api:latest
          name: prism-api
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}

